#!/usr/bin/env node

const source_path = process.argv[2]

if (process.argv.includes("--version")) {
  const package_info = require('./package.json');
  console.log(package_info.version)
  process.exit(0)
}

function getArticle(html) {
  const createDOMPurify = require('dompurify');
  const { Readability } = require('@mozilla/readability');
  const { JSDOM } = require('jsdom');
  
  const window = new JSDOM("").window
  const DOMPurify = createDOMPurify(window)
  const clean = DOMPurify.sanitize(html)
  
  const doc = new JSDOM(clean, {url: "https://example.com/unused-placeholder-url"})
  
  const reader = new Readability(doc.window.document)
  return reader.parse()
}

const fs = require("fs");

const html = fs.readFileSync(source_path).toString()
console.log(JSON.stringify(getArticle(html)))

